### ISSUE TITLE
[WIN] When creating a new unsaved file, autocompletion does not work in it

### ISSUE THREAD

**Issue by hazratisulton** [smallcloudai/refact-sublime#10]
Create new file - Try completion in it -> Completion not working
In console:
`Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 959, in on_modified
    run_view_callbacks('on_modified', view_id)
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 741, in run_view_callbacks
    callback(v, *args)
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 162, in profiler
    return event_handler(*args)
  File "C:\Users\agzam\AppData\Roaming\Sublime Text\Packages\refact\__init__.py", line 21, in on_modified
    session = refact_session_manager.get_session(view)
  File "C:\Users\agzam\AppData\Roaming\Sublime Text\Packages\refact\src\refact_sessions.py", line 35, in get_session
    self.views[view_id] = RefactSession(view, self.get_connection, view_id == "UI")
  File "C:\Users\agzam\AppData\Roaming\Sublime Text\Packages\refact\src\refact_sessions.py", line 58, in __init__
    self.connection().load_document(self.file_name, get_text(self.view), self.languageId)
  File "C:\Users\agzam\AppData\Roaming\Sublime Text\Packages\refact\src\refact_lsp.py", line 19, in load_document
    uri = pathlib.Path(file_name).as_uri()
  File "./python3.8/pathlib.py", line 748, in as_uri
ValueError: relative path can't be expressed as a file URI
`
If you save the file, the compliment will start working

**Versions:**
Sublime plugin v 0.0.1
Sublime Text Build 4169

**Comment by olegklimov** [comment]
An interesting one. We use URI in refact-lsp.

**Comment by hazratisulton** [comment]
https://github.com/smallcloudai/refact-sublime/pull/15 - fixed
